import {analyze,tiers,key} from './model.mjs';
import {LABELS} from './backtest.mjs';
const $=id=>document.getElementById(id),fmt=t=>t.nums.map(n=>String(n).padStart(2,'0')).join(' '),money=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD'});
let data,rows=[],scope=[],analysis,plays=[],visible=100,rankWorker,worker,run,journal=[],wins=[];
const status=s=>$('status').textContent=s;
function table(id,list,cols){const box=$(id);box.replaceChildren();if(!list.length){box.textContent='No matching records.';return;}const t=document.createElement('table'),head=t.createTHead().insertRow(),body=t.createTBody();function render(){body.replaceChildren();for(const r of list){const tr=body.insertRow();for(const c of cols)tr.insertCell().textContent=String(c.show?c.show(r):c.value(r));}}for(const c of cols){const th=document.createElement('th'),button=document.createElement('button');button.textContent=c.name+' ↕';let desc=true;button.onclick=()=>{list.sort((a,b)=>{const x=c.value(a),y=c.value(b);return (typeof x==='number'?x-y:String(x).localeCompare(String(y)))*(desc?-1:1);});desc=!desc;render();};th.append(button);head.append(th);}render();box.append(t);}
function persist(){localStorage.setItem('jerseycash5-journal-v1',JSON.stringify({journal,wins}));}
try{const saved=JSON.parse(localStorage.getItem('jerseycash5-journal-v1')||'{"journal":[],"wins":[]}');if(!Array.isArray(saved.journal)||!Array.isArray(saved.wins))throw Error('Invalid saved journal');journal=saved.journal;wins=saved.wins;let recovered=false;for(const r of journal){if(r.state==='running'){r.state='Interrupted — last announced numbers retained';recovered=true;}}if(recovered)persist();}catch(e){status('Saved journal could not be loaded: '+e.message);$('simulate').disabled=true;}
const playCols=[{name:'ID',value:r=>r.id},{name:'Numbers',value:fmt},{name:'Research score',value:r=>r.score,show:r=>r.score.toFixed(5)},{name:'Avg draws overdue',value:r=>r.avgGap},{name:'Historical exact matches',value:r=>r.pastHits},{name:'Why this set scored',value:r=>r.explanation}];
function journalRows(){return journal.flatMap(r=>{const list=r.results.slice();if(r.last&&!list.some(d=>d.index===r.last.index))list.push(r.last);return list.map(d=>({...d,run:r.id,seed:r.seed,mode:r.mode,method:r.method,state:r.state}));});}
function renderSaved(){table('wins',wins.slice().reverse().slice(0,1000),[{name:'ID',value:r=>r.id},{name:'Mock date',value:r=>r.date},{name:'Ticket numbers',value:fmt},{name:'Winning draw',value:r=>fmt(r.draw)},{name:'Bullseye',value:r=>r.draw.bullseye},{name:'Prize tier',value:r=>r.tier,show:r=>tiers[r.tier]},{name:'Winning tickets represented',value:r=>r.multiplicity},{name:'Crowd ticket ID',value:r=>r.ticketId},{name:'Avg draws overdue',value:r=>r.avgGap},{name:'Historical exact matches',value:r=>r.pastHits},{name:'Run ID',value:r=>r.runId},{name:'Seed',value:r=>r.seed}]);table('calendar',journalRows().slice().reverse().slice(0,500),[{name:'Mock date',value:r=>r.date},{name:'Winning draw',value:r=>fmt(r.draw)},{name:'Bullseye',value:r=>r.draw.bullseye},{name:'Jackpot tickets',value:r=>r.counts?.[0]??'Not scored'},{name:'Second prize tickets',value:r=>r.counts?.[1]??'—'},{name:'Third prize tickets',value:r=>r.counts?.[2]??'—'},{name:'Run state',value:r=>r.state},{name:'Seed',value:r=>r.seed}]);}
function renderHistory(){const selected=rows.filter(r=>(!$('year').value||r.date.startsWith($('year').value))&&($('paid').value!=='yes'||r.jackpot_payout>0)&&(!$('date').value||r.date===$('date').value));table('history',selected.slice().reverse().slice(0,visible),[{name:'Date',value:r=>r.date},{name:'Draw',value:r=>r.draw_type},{name:'Winning numbers',value:fmt},{name:'Bullseye',value:r=>r.bullseye??'Not offered'},{name:'XTRA',value:r=>r.xtra},{name:'Official 5/5 payout',value:r=>r.jackpot_payout,show:r=>money(r.jackpot_payout)}]);$('more').disabled=visible>=selected.length;}
function refreshScope(){if(rankWorker)rankWorker.terminate();rankWorker=null;scope=rows.filter(r=>$('drawType').value==='all'||r.draw_type==='regular');if($('window').value!=='all')scope=scope.slice(-Number($('window').value));analysis=analyze(scope);$('scope').textContent=`${scope.length.toLocaleString()} draws analyzed; ${analysis.paid.toLocaleString()} jackpot-paid draws. Counts below include Bullseye within the five numbers.`;table('numbers',analysis.numbers.slice().sort((a,b)=>b.hits-a.hits||a.n-b.n),[{name:'Number',value:r=>r.n},{name:'All appearances',value:r=>r.hits},{name:'Jackpot-paid appearances',value:r=>r.jackpotHits},{name:'Recent 90 draws',value:r=>r.recentHits},{name:'Draws overdue',value:r=>r.gap},{name:'Last appearance',value:r=>r.lastDate},{name:'Bullseye appearances',value:r=>r.bullseyeHits}]);table('pairs',[...analysis.pairs.values()].sort((a,b)=>b.hits-a.hits).slice(0,100),[{name:'Pair',value:r=>r.numbers},{name:'All appearances',value:r=>r.hits},{name:'Jackpot-paid appearances',value:r=>r.jackpotHits}]);$('rank').disabled=false;plays=[];table('plays',[],playCols);}
function report(r){if(!r?.last)return;const d=r.last;const prizes=['Shared jackpot',500,250,30,15,5];table('report',tiers.map((name,k)=>({name,count:d.counts?.[k]??'Waiting for score',prize:prizes[k]})),[{name:'Prize tier',value:r=>r.name},{name:'Winning tickets',value:r=>r.count},{name:'Current base prize',value:r=>r.prize}]);status(`${r.state} · ${r.completed} mock draws · ${d.date} · ${fmt(d.draw)} · Bullseye ${d.draw.bullseye} · seed ${r.seed}`);}
function finish(state){worker?.terminate();worker=null;let saveError;if(run){run.state=state;try{persist();}catch(e){saveError=e;}}$('simulate').disabled=false;$('stop').disabled=true;report(run);renderSaved();if(saveError)status('Saving failed. Export before leaving: '+saveError.message);}
function download(name,list){if(!list.length){status('No records to export.');return;}const cols=[...new Set(list.flatMap(r=>Object.keys(r)))],q=v=>'"'+String(typeof v==='object'?JSON.stringify(v):v??'').replaceAll('"','""')+'"';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([cols.map(q).join(',')+'\n'+list.map(r=>cols.map(c=>q(r[c])).join(',')).join('\n')],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('rank').onclick=()=>{rankWorker?.terminate();$('rank').disabled=true;status('Scoring all five-number combinations…');rankWorker=new Worker('worker.mjs',{type:'module'});rankWorker.onmessage=({data:d})=>{rankWorker.terminate();rankWorker=null;$('rank').disabled=false;if(d.type==='error'){status(d.message);return;}plays=d.plays;table('plays',plays.slice(),playCols);status('Research ranking complete. Scores describe history; they are not win probabilities.');};rankWorker.onerror=e=>{rankWorker.terminate();rankWorker=null;$('rank').disabled=false;status(e.message);};rankWorker.postMessage({task:'rank',rows:scope,method:$('algorithm').value,exclude:$('exclude').checked});};
for(const id of ['window','drawType'])$(id).onchange=()=>{refreshScope();$('rank').click();};for(const id of ['algorithm','exclude'])$(id).onchange=()=>$('rank').click();for(const id of ['year','paid','date'])$(id).onchange=()=>{visible=100;renderHistory();};$('more').onclick=()=>{visible+=100;renderHistory();};
$('exportHistory').onclick=()=>download('jersey-cash5-official-history.csv',rows);$('exportPlays').onclick=()=>download('jersey-cash5-research-plays.csv',plays);$('exportWins').onclick=()=>download('jersey-cash5-mock-winning-tickets.csv',wins);$('exportRuns').onclick=()=>download('jersey-cash5-mock-drawing-journal.csv',journalRows());$('stop').onclick=()=>finish('Stopped');
$('simulate').onclick=()=>{const crowd=Number($('crowd').value),draws=Number($('draws').value),start=$('start').value;if(!Number.isInteger(crowd)||crowd<1||crowd>1000000||!Number.isInteger(draws)||draws<1||draws>1000||!/^\d{4}-\d{2}-\d{2}$/.test(start)||new Date(start+'T12:00:00Z').toISOString().slice(0,10)!==start){status('Enter valid agents, draws, and start date.');return;}const seed=crypto.getRandomValues(new Uint32Array(1))[0],runAnalysis=analyze(scope);run={id:crypto.randomUUID(),seed,crowd,draws,start,mode:$('mode').value,method:$('crowdMethod').value,until:$('until').checked,state:'running',completed:0,results:[],analysisFirst:scope[0].date,analysisLast:scope.at(-1).date};journal.push(run);try{persist();worker=new Worker('worker.mjs',{type:'module'});}catch(e){run.state='Failed to start';status(e.message);return;}$('simulate').disabled=true;$('stop').disabled=false;status('Creating fixed crowd…');worker.onerror=e=>{finish('Failed');status(e.message);};worker.onmessage=({data:d})=>{try{if(d.type==='drawing'){run.last=d;persist();report(run);}else if(d.type==='result'){run.last=d;run.completed=d.index;run.results.push(d);for(const t of d.winners)wins.push({...t,id:crypto.randomUUID(),date:d.date,draw:d.draw,seed,runId:run.id,method:run.method,avgGap:t.nums.reduce((s,n)=>s+runAnalysis.numbers[n-1].gap,0)/5,pastHits:runAnalysis.exact.get(key(t))||0});persist();report(run);}else if(d.type==='done')finish('Completed');else if(d.type==='error'){finish('Failed');status(d.message);}}catch(e){worker?.terminate();worker=null;run.state='Stopped — save failed';$('simulate').disabled=false;$('stop').disabled=true;renderSaved();status('Saving failed; last numbers retained in memory. Export before leaving: '+e.message);}};worker.postMessage({...run,rows:scope});};
renderSaved();if(journal.length)report(journal.at(-1));
try{let failure;for(const url of ['https://raw.githubusercontent.com/daaxelv/pick3-stats/main/jerseycash5/data/history.json','data/history.json']){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.draws)||d.regular_draws<1)throw Error('Invalid history');data=d;break;}catch(e){failure=e;}}if(!data)throw failure;rows=data.draws;$('coverage').textContent=`${data.regular_draws.toLocaleString()} regular + ${data.promotional_draws} promotional draws · ${data.first_date} through ${data.last_date} · ${data.missing_dates.length} missing scheduled dates. Checked ${data.checked_at}`;$('start').value=data.last_date;for(const y of [...new Set(rows.map(r=>r.date.slice(0,4)))].sort().reverse()){const o=document.createElement('option');o.value=y;o.textContent=y;$('year').append(o);}refreshScope();renderHistory();$('simulate').disabled=false;$('backtestRun').disabled=false;$('rank').click();}catch(e){$('coverage').textContent='History unavailable: '+e.message;}
let backtestWorker,backtestResult;
const btStatus=s=>$('backtestStatus').textContent=s,modelCol={name:'Model',value:r=>LABELS[r.model]},matchCols=[2,3,4,5].map(n=>({name:n===5?'5/5 matches':`${n}/5 matches`,value:r=>r.counts[n]}));
function renderBacktest(){
  if(!backtestResult)return;const r=backtestResult,b=r.baseline;
  btStatus(`Completed · ${r.firstDate} through ${r.lastDate} · ${r.summary[0].draws} actual draws · 10 tickets per model per draw · seed ${r.settings.seed}. Random 3+ match totals: ${b.min}–${b.max}, mean ${b.mean.toFixed(2)} across ${r.settings.baselineTrials} trials.`);
  table('backtestSummary',r.summary.slice(),[modelCol,{name:'Actual draws',value:r=>r.draws},{name:'Tickets scored',value:r=>r.ticketsScored},...matchCols,{name:'3+ matches',value:r=>r.threePlus},{name:'Difference vs random mean',value:r=>r.baselineDifference,show:r=>r.baselineDifference.toFixed(2)},{name:'Unique sets',value:r=>r.uniqueSets},{name:'Monthly repeat slots',value:r=>r.repeatedSlots},{name:'Total monthly selection slots',value:r=>r.selectionSlots}]);
  const matches=r=>($('backtestModel').value==='all'||r.model===$('backtestModel').value)&&($('backtestMonth').value==='all'||r.month===$('backtestMonth').value);
  table('backtestMonthly',r.monthly.filter(matches),[modelCol,{name:'Month',value:r=>r.month},{name:'Training draws',value:r=>r.trainingDraws},{name:'Training through',value:r=>r.trainingThrough},{name:'First tested date',value:r=>r.testFirst},{name:'Last tested date',value:r=>r.testLast},{name:'Actual draws',value:r=>r.draws},...matchCols,{name:'3+ matches',value:r=>r.threePlus},{name:'Prior-month repeats',value:r=>r.repeatedFromPriorMonth??'First month'},{name:'Random 3+ range',value:r=>`${r.baselineMin}–${r.baselineMax}`}]);
  table('backtestDetails',r.details.filter(matches),[modelCol,{name:'Date',value:r=>r.date},{name:'Selected ticket',value:r=>r.ticket},{name:'Actual winning draw',value:r=>r.winning},{name:'Matches',value:r=>r.matches},{name:'Bullseye',value:r=>r.bullseye??'Not offered'},{name:'Ticket includes Bullseye',value:r=>r.includesBullseye===null?'Not offered':r.includesBullseye?'Yes':'No'}]);
  table('backtestSelections',r.selections.filter(matches),[modelCol,{name:'Month',value:r=>r.month},{name:'Rank',value:r=>r.rank},{name:'Selected ticket',value:r=>r.ticket},{name:'Training through',value:r=>r.trainingThrough}]);
}
function backtestMonths(){const select=$('backtestMonth');select.replaceChildren();for(const month of ['all',...[...new Set(backtestResult.monthly.map(r=>r.month))]]){const o=document.createElement('option');o.value=month;o.textContent=month==='all'?'All months':month;select.append(o);}}
try{const saved=JSON.parse(localStorage.getItem('jerseycash5-backtest-v1')||'null');if(saved?.version===1&&Array.isArray(saved.summary)&&saved.summary.length===7&&Array.isArray(saved.monthly)&&Array.isArray(saved.details)&&Array.isArray(saved.selections)&&saved.baseline&&saved.settings){backtestResult=saved;backtestMonths();renderBacktest();}}catch(e){btStatus('Saved backtest could not be loaded: '+e.message);}
$('backtestRun').onclick=()=>{
  const seed=Number($('backtestSeed').value);if($('backtestSeed').value===''||!Number.isInteger(seed)||seed<0||seed>4294967295){btStatus('Enter a whole-number seed from 0 to 4294967295.');return;}
  try{backtestWorker=new Worker('backtest-worker.mjs',{type:'module'});}catch(e){btStatus('Backtest could not start: '+e.message);return;}
  $('backtestRun').disabled=true;$('backtestStop').disabled=false;btStatus('Testing historical selections against later actual draws… Previous completed report stays available until this run finishes.');
  const finish=()=>{backtestWorker?.terminate();backtestWorker=null;$('backtestRun').disabled=false;$('backtestStop').disabled=true;};
  backtestWorker.onmessage=({data:d})=>{if(d.type==='progress'){btStatus(`Scoring month ${d.index} of ${d.total} · ${d.month} · using only earlier regular draws…`);return;}finish();if(d.type==='error'){btStatus('Backtest failed: '+d.message);return;}backtestResult=d.result;backtestMonths();renderBacktest();try{localStorage.setItem('jerseycash5-backtest-v1',JSON.stringify(backtestResult));}catch(e){btStatus($('backtestStatus').textContent+' Saving failed; export this report before leaving: '+e.message);}};
  backtestWorker.onerror=e=>{finish();btStatus('Backtest failed: '+e.message);};
  backtestWorker.postMessage({rows,settings:{window:$('backtestWindow').value,seed}});
};
$('backtestStop').onclick=()=>{backtestWorker?.terminate();backtestWorker=null;$('backtestRun').disabled=false;$('backtestStop').disabled=true;btStatus('Cancelled. The previous completed report is retained; partial results are not saved.');};
for(const id of ['backtestModel','backtestMonth'])$(id).onchange=renderBacktest;
$('backtestExport').onclick=()=>{if(!backtestResult){btStatus('Complete a backtest before exporting.');return;}const r=backtestResult;download('jersey-cash5-historical-backtest.csv',[{record:'settings',...r.settings,firstDate:r.firstDate,lastDate:r.lastDate,baseline:r.baseline},...r.summary.map(x=>({record:'summary',...x})),...r.monthly.map(x=>({record:'month',...x})),...r.selections.map(x=>({record:'selection',...x})),...r.details.map(x=>({record:'match',...x}))]);};
if('serviceWorker' in navigator)navigator.serviceWorker.register('../service-worker.js').catch(()=>{});
