import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import * as model from './model.mjs';import {normalize,snapshot,nextDate} from './data.mjs';
const history=JSON.parse(fs.readFileSync(new URL('./data/history.json',import.meta.url)));
test('Official archive has complete current-format calendar, no conflicting main dates, and paid-draw counts',()=>{
  const s=snapshot(history.draws);assert.equal(s.first_date,'2020-06-29');assert.equal(s.regular_draws,history.regular_draws);assert.deepEqual(s.missing_dates,[]);assert.equal(s.promotional_draws,history.promotional_draws);assert.equal(s.jackpot_paid_draws,history.jackpot_paid_draws);
  const regular=history.draws.filter(r=>r.draw_type==='regular');assert.equal(new Set(regular.map(r=>r.date)).size,regular.length);
  for(const r of history.draws){assert.equal(r.nums.length,5);assert.equal(new Set(r.nums).size,5);assert.ok(r.nums.every(n=>n>=1&&n<=45));if(r.draw_type==='regular'&&r.date>='2024-07-01')assert.ok(r.nums.includes(r.bullseye));}
});
test('Parser keeps Bullseye inside five, labels promotions, deduplicates overlap and rejects conflicts',()=>{
  const r={date:'10/07/2026',nums:[1,2,6,10,21],bullseye:2,xtra:3,jackpot_payout:0};assert.equal(normalize([r,r]).length,1);
  assert.equal(normalize([r,{...r,date:'Green Ball Double Draw',bullseye:null}])[0].draw_type,'promotion');
  for(const bad of [{...r,nums:[1,1,6,10,21]},{...r,bullseye:45},{...r,bullseye:null},{...r,jackpot_payout:null},{...r,xtra:7}])assert.throws(()=>normalize([bad]));
  assert.throws(()=>normalize([r,{...r,jackpot_payout:1000}]),/Conflicting/);
});
test('Calendar skips Christmas and handles leap day; coverage reports real gaps',()=>{assert.equal(nextDate('2026-12-24'),'2026-12-26');assert.equal(nextDate('2024-02-28'),'2024-02-29');const r=history.draws[0];assert.deepEqual(snapshot([{...r,date:'2026-01-01'},{...r,date:'2026-01-03'}]).missing_dates,['2026-01-02']);});
test('Jackpot frequencies count paid draws once and Bullseye contributes once',()=>{const a=model.analyze([{date:'2026-01-01',nums:[1,2,3,4,5],bullseye:2,jackpot_payout:100000},{date:'2026-01-02',nums:[1,6,7,8,9],bullseye:1,jackpot_payout:0}]);assert.equal(a.numbers[0].hits,2);assert.equal(a.numbers[0].jackpotHits,1);assert.equal(a.paid,1);assert.equal(a.pairs.get('1-2').hits,1);assert.equal(a.numbers.reduce((s,n)=>s+n.hits,0),10);});
test('All-space counts match exhaustive scoring and witnesses match each top tier',()=>{const d={nums:[1,2,3,4,5],bullseye:3},counts=Array(6).fill(0);for(let a=1;a<=41;a++)for(let b=a+1;b<=42;b++)for(let c=b+1;c<=43;c++)for(let e=c+1;e<=44;e++)for(let f=e+1;f<=45;f++){const k=model.tier({nums:[a,b,c,e,f]},d);if(k>=0)counts[k]++;}assert.deepEqual(counts,model.fullCounts());assert.equal(model.choose(45,5),model.TOTAL);model.witnesses(d).forEach((t,k)=>assert.equal(model.tier(t,d),k));});
test('Ranking scores every candidate and excludes repeats without fixing 04',()=>{const a=model.analyze(history.draws.filter(r=>r.draw_type==='regular'));for(const method of ['blended','jackpot','pairs']){const plays=model.rank(a,method,true);assert.equal(plays.length,10);assert.equal(new Set(plays.map(model.key)).size,10);for(const t of plays){assert.equal(t.id,model.key(t));assert.ok(!a.exact.has(model.key(t)));assert.equal(t.score,model.score(t.nums,a,method));}assert.ok(plays.every((t,i)=>i===0||t.score<=plays[i-1].score));}const u=model.rank(a,'uniform');assert.ok(u.some(t=>!t.nums.includes(4)));});
function simulate(o){const events=[];const source=fs.readFileSync(new URL('./worker.mjs',import.meta.url),'utf8').replace(/^import .*;$/gm,'');const context={...model,nextDate,Uint8Array,self:{postMessage:r=>events.push(r)}};vm.runInNewContext(source,context);context.self.onmessage({data:o});return JSON.parse(JSON.stringify(events));}
test('100k-agent crowd completes and seed replay retains ticket IDs and correctly scored wins',()=>{const options={crowd:100000,draws:3,start:'2026-12-23',mode:'crowd',method:'uniform',seed:104,rows:history.draws,until:false};const e=simulate(options);assert.deepEqual(e,simulate(options));assert.equal(e.at(-1).type,'done');const results=e.filter(r=>r.type==='result');assert.equal(results.length,3);assert.equal(results[1].date,'2026-12-26');for(const r of results){assert.ok(r.counts.reduce((s,n)=>s+n,0)<=options.crowd);for(const t of r.winners){assert.equal(model.tier(t,r.draw),t.tier);assert.ok(t.ticketId>=1&&t.ticketId<=100000);}assert.equal(r.winners.length,r.counts.slice(0,3).reduce((s,n)=>s+n,0));}});
test('Full-space run announces numbers before score and stops at saved jackpot',()=>{const e=simulate({crowd:100000,draws:30,start:'2026-10-08',mode:'full',method:'uniform',seed:1,rows:history.draws,until:true});assert.equal(e[0].type,'drawing');assert.equal(e[1].type,'result');assert.deepEqual(e[0].draw,e[1].draw);assert.deepEqual(e[1].counts,model.fullCounts());assert.equal(e[1].winners[1].multiplicity,160);assert.equal(e.at(-1).type,'done');assert.equal(e.filter(r=>r.type==='result').length,1);});
test('Crowd weighting and crowd size cannot change the mock winning draws',()=>{const options={crowd:1000,draws:2,start:'2026-10-08',mode:'crowd',method:'uniform',seed:5,rows:history.draws,until:false};const draws=o=>simulate(o).filter(e=>e.type==='drawing').map(e=>e.draw);assert.deepEqual(draws(options),draws({...options,crowd:10000,method:'jackpot'}));});
