import {parseRows,scoreModel,backtest,candidateTickets} from './model.js';
const $=id=>document.getElementById(id), storeKey='m4l-god-research-list-v1';
let rows=[],source='',latest=[],lastRun=null;
const pad=n=>String(n).padStart(2,'0'),ticket=t=>t.nums.map(pad).join('-')+' MB:'+pad(t.mb);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toFixed(3);
function status(message){$('status').textContent=message;}
function setData(text,label){const parsed=parseRows(text);if(parsed.length<31)throw Error('Need at least 31 distinct dated M4L draws.');rows=parsed;source=label;latest=[];lastRun=null;$('rankings').textContent='Run a model to create a list.';$('tickets').textContent='';$('backtest').textContent='Run a model to view the comparison.';$('coverage').textContent=`${rows.length} distinct draws · ${rows[0].date} to ${rows.at(-1).date} · ${source}`;status('History loaded. Choose Run research model.');}
async function loadLive(){status('Loading current M4L results…');try{const response=await fetch('../data/nj_numbers_canonical.csv',{cache:'no-store'});if(!response.ok)throw Error('Results feed returned '+response.status);setData(await response.text(),'site results feed');}catch(err){try{setData(await (await fetch('research-sample-60.csv')).text(),'supplied 60-draw sample (live feed unavailable)');}catch(e){status('Could not load results: '+err.message);}}}
$('live').onclick=loadLive;
$('sample').onclick=async()=>{try{setData(await(await fetch('research-sample-60.csv')).text(),'supplied 60-draw sample');}catch(err){status(err.message);}};
$('upload').onchange=async event=>{try{const file=event.target.files[0];if(file)setData(await file.text(),'uploaded '+file.name);}catch(err){status(err.message);}};
$('model').onchange=()=>{$('modelNote').textContent=$('model').value==='physical'?'Physical model uses historical frequency, recency, gaps, and carryover. No real ball measurements were supplied, so its physical effect is zero.':$('model').value==='uniform'?'Uniform baseline gives every main number and Millionaire Ball equal model weight.':'Origin uses frequency, recent results, gaps, carryover, transitions, weekday, and separate Millionaire Ball scoring. Cash4Life transfer is off; the model does not claim knowledge of drawing hardware.';};
function saved(){try{const list=JSON.parse(localStorage.getItem(storeKey)||'[]');return Array.isArray(list)?list:[];}catch{return [];}}
function write(list){try{localStorage.setItem(storeKey,JSON.stringify(list));renderSaved();}catch{status('Browser storage unavailable; export the list before leaving.');}}
window.saveTicket=i=>{const t=latest[i];if(!t||!lastRun)return;const list=saved(),key=ticket(t);if(list.some(x=>x.ticket===key && x.model===lastRun.model)){status('That set is already in this model’s saved list.');return;}list.unshift({ticket:key,...lastRun,savedAt:new Date().toISOString()});write(list.slice(0,500));status('Saved '+key+' to the research list.');};
window.removeTicket=i=>{const list=saved();list.splice(i,1);write(list);};
function renderSaved(){const list=saved();$('saved').innerHTML=list.length?'<div class="tableWrap"><table><thead><tr><th>Set</th><th>Model</th><th>Last draw on file</th><th>Source</th><th></th></tr></thead><tbody>'+list.map((x,i)=>`<tr><td>${escape(x.ticket)}</td><td>${escape(x.model)} · ${escape(x.profile)}</td><td>${escape(x.date)}</td><td>${escape(x.source)}</td><td><button type="button" onclick="removeTicket(${i})">Remove</button></td></tr>`).join('')+'</tbody></table></div>':'<p class="small">No saved research tickets yet.</p>';}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(saved(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='m4l-research-tickets.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function renderTest(report,minTrain){$('backtest').innerHTML=`<p class="small">${rows.length-minTrain} held-out draws; each model trained on at least ${minTrain}. Higher Top 5/10 or MB top-one is better; lower mean winner rank and less negative log score are better. Top lists alone do not prove a signal.</p><div class="tableWrap"><table><thead><tr><th>Model</th><th>Top 5 hits / draw</th><th>Top 10 hits / draw</th><th>Mean winner rank</th><th>MB top-one rate</th><th>Main log score</th><th>MB log score</th></tr></thead><tbody>`+Object.entries(report).map(([key,r])=>`<tr><td>${escape(key)}</td><td class="num">${fmt(r.top5)}</td><td class="num">${fmt(r.top10)}</td><td class="num">${fmt(r.rank)}</td><td class="num">${(r.mbTop1*100).toFixed(1)}%</td><td class="num">${fmt(r.logMain)}</td><td class="num">${fmt(r.logMB)}</td></tr>`).join('')+'</tbody></table></div>';}
let sort={key:'score',dir:-1};
function renderTickets(){let list=latest.map((t,i)=>({...t,original:i+1}));list.sort((a,b)=>{const av=sort.key==='ticket'?ticket(a):a[sort.key],bv=sort.key==='ticket'?ticket(b):b[sort.key];return (typeof av==='string'?av.localeCompare(bv):av-bv)*sort.dir || a.original-b.original;});$('tickets').innerHTML='<h2>Candidate sets</h2><p class="small">Ranked by model sampling score. The original # stays attached when you sort. These are research examples, not higher-odds tickets.</p><div class="tableWrap"><table><thead><tr>'+[['original','#'],['ticket','Set'],['score','Model score']].map(([key,label])=>`<th><button type="button" data-sort="${key}">${label}${sort.key===key?(sort.dir===1?' ▲':' ▼'):' ↕'}</button></th>`).join('')+'<th>Save</th></tr></thead><tbody>'+list.map(t=>`<tr><td>${t.original}</td><td>${escape(ticket(t))}</td><td class="num">${fmt(t.score)}</td><td><button type="button" onclick="saveTicket(${t.original-1})">Save set</button></td></tr>`).join('')+'</tbody></table></div>';$('tickets').querySelectorAll('[data-sort]').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.sort;sort=sort.key===key?{key,dir:-sort.dir}:{key,dir:key==='score'?-1:1};renderTickets();});}
$('run').onclick=()=>{if(!rows.length){status('Load M4L results first.');return;}try{status('Comparing models against earlier draws…');const minTrain=rows.length>=90?60:30,profile=$('profile').value,model=$('model').value;const report=backtest(rows,profile,minTrain);renderTest(report,minTrain);
const next=new Date(rows.at(-1).date+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+1);const target=next.toISOString().slice(0,10),weights=scoreModel(rows,target,model,profile);const sorted=Array.from({length:58},(_,i)=>i+1).sort((a,b)=>weights.main[b-1]-weights.main[a-1]||a-b),balls=Array.from({length:5},(_,i)=>i+1).sort((a,b)=>weights.mb[b-1]-weights.mb[a-1]||a-b);
$('rankings').innerHTML=`<p class="small">Data through ${rows.at(-1).date}. Research target: ${target}. Main weights are ranking values, not calibrated draw probabilities.</p><p><strong>Top 20 main numbers:</strong> ${sorted.slice(0,20).map(pad).join(' · ')}</p><p><strong>Millionaire Ball order:</strong> ${balls.map(pad).join(' · ')}</p>`;
latest=candidateTickets(weights,Number($('count').value),$('only04').checked);lastRun={model,profile,source,date:rows.at(-1).date};sort={key:'score',dir:-1};renderTickets();status('Compared '+(rows.length-minTrain)+' held-out draws and generated '+latest.length+' research sets.');}catch(err){status('Model error: '+err.message);}};
renderSaved();loadLive();
