import {candidates,stats,key,tiers,TOTAL,fullCounts} from './model.mjs';
const $=id=>document.getElementById(id),fmt=t=>t.nums.map(n=>String(n).padStart(2,'0')).join(' ')+' + PB '+String(t.pb).padStart(2,'0');
let statMain=[],history=[],current=[],plays=[],visible=100,worker=null,run=null,journal=[],wins=[];
const status=s=>$('status').textContent=s;
function load(key){const raw=localStorage.getItem(key);return raw?JSON.parse(raw):[];}
try{journal=load('powerball-runs-v1');wins=load('powerball-wins-v1');for(const r of journal)if(r.state==='running')r.state='Interrupted — last draw retained';}catch(e){status('Saved data could not be read: '+e.message);}
function persist(){localStorage.setItem('powerball-runs-v1',JSON.stringify(journal));localStorage.setItem('powerball-wins-v1',JSON.stringify(wins));}
// Values are written through textContent, including saved browser data.
function table(id,rows,cols){const box=$(id);box.replaceChildren();if(!rows.length){box.textContent='No matching records.';return;}const t=document.createElement('table'),head=t.createTHead().insertRow(),body=t.createTBody();const render=()=>{body.replaceChildren();rows.forEach(r=>{const tr=body.insertRow();cols.forEach(c=>tr.insertCell().textContent=String(c.value(r)));});};cols.forEach(c=>{const th=document.createElement('th'),b=document.createElement('button');b.textContent=c.name+' ↕';let desc=true;b.onclick=()=>{rows.sort((a,b)=>{const x=c.value(a),y=c.value(b);return (typeof x==='number'?x-y:String(x).localeCompare(String(y)))*(desc?-1:1);});desc=!desc;render();};th.append(b);head.append(th);});render();box.append(t);}
const ticketCols=[{name:'Research score',value:r=>r.score??'—'},{name:'ID',value:r=>r.id},{name:'Numbers',value:fmt},{name:'Avg draws overdue',value:r=>r.avgGap},{name:'Historical exact matches',value:r=>r.pastHits}];
function renderHistory(){let rows=$('era').value==='all'?history:current;if($('focus').checked)rows=rows.filter(r=>r.nums.includes(4)&&r.pb===4);if($('searchDate').value)rows=rows.filter(r=>r.date===$('searchDate').value);table('history',rows.slice().reverse().slice(0,visible),[{name:'Date',value:r=>r.date},{name:'Winning numbers',value:fmt},{name:'Power Play',value:r=>r.power_play??'Not recorded'}]);$('more').disabled=visible>=rows.length;}
function renderWins(){table('wins',wins.slice(),[{name:'ID',value:r=>r.id},{name:'Mock draw date',value:r=>r.date},{name:'Ticket',value:fmt},{name:'Winning draw',value:r=>fmt(r.draw)},{name:'Prize tier',value:r=>tiers[r.tier].label},{name:'Winning tickets represented',value:r=>r.multiplicity},{name:'Avg draws overdue',value:r=>r.avgGap},{name:'Historical exact matches',value:r=>r.pastHits},{name:'Crowd ticket ID',value:r=>r.ticketId},{name:'Seed',value:r=>r.seed}]);}
function calendarRows(){return journal.flatMap(r=>{const rows=r.results.slice();if(r.last&&!rows.some(d=>d.index===r.last.index))rows.push(r.last);return rows.map(d=>({run:r.id,seed:r.seed,mode:r.mode,crowd:r.crowd,state:r.state,...d}));});}
function renderCalendar(){table('calendar',calendarRows().slice().reverse().slice(0,500),[{name:'Mock date',value:r=>r.date},{name:'Winning draw',value:r=>fmt(r.draw)},{name:'Jackpot tickets',value:r=>r.counts?.[0]??'Interrupted before scoring'},{name:'2nd tickets',value:r=>r.counts?.[1]??'—'},{name:'3rd tickets',value:r=>r.counts?.[2]??'—'},{name:'Run state',value:r=>r.state},{name:'Seed',value:r=>r.seed}]);}
function report(r){if(!r?.last)return;table('report',tiers.map((t,i)=>({name:t.label,count:r.last.counts?.[i]??'Awaiting result',odds:(TOTAL/fullCounts()[i]).toFixed(2)})),[{name:'Prize',value:r=>r.name},{name:'Winners this draw',value:r=>r.count},{name:'Odds · 1 in',value:r=>r.odds}]);status(`${r.state} · ${r.completed||0} draws · ${r.last.date} · ${fmt(r.last.draw)} · seed ${r.seed}`);}
function download(name,rows){const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))],q=v=>'"'+String(typeof v==='object'?JSON.stringify(v):v??'').replaceAll('"','""')+'"';const blob=new Blob([cols.map(q).join(',')+'\n'+rows.map(r=>cols.map(c=>q(r[c])).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('rank').onclick=()=>{plays=candidates(current,$('algorithm').value,$('focus').checked);table('candidates',plays.slice(),ticketCols);};
for(const id of ['era','focus','searchDate'])$(id).onchange=()=>{visible=100;renderHistory();};$('more').onclick=()=>{visible+=100;renderHistory();};
$('exportHistory').onclick=()=>download('powerball-history.csv',history);$('exportWins').onclick=()=>download('powerball-winning-tickets.csv',wins);$('exportRuns').onclick=()=>download('powerball-draw-journal.csv',calendarRows());
function finish(state){if(worker){worker.terminate();worker=null;}if(run){run.state=state;try{persist();}catch(e){status('Storage full or unavailable. Export the current journal: '+e.message);}}$('simulate').disabled=false;$('stop').disabled=true;report(run);renderCalendar();}
$('stop').onclick=()=>finish('Stopped');
$('simulate').onclick=()=>{const crowd=Number($('crowd').value),draws=Number($('draws').value),start=$('start').value;if(!Number.isInteger(crowd)||crowd<1||crowd>1000000||!Number.isInteger(draws)||draws<1||draws>10000||!/^\d{4}-\d{2}-\d{2}$/.test(start)){status('Enter 1–1,000,000 tickets, 1–10,000 draws and a start date.');return;}const seed=crypto.getRandomValues(new Uint32Array(1))[0];run={id:crypto.randomUUID(),seed,mode:$('mode').value,crowd,focus:$('focus').checked,draws,start,until:$('until').checked,state:'running',completed:0,results:[]};journal.push(run);try{persist();worker=new Worker('worker.mjs',{type:'module'});}catch(e){run.state='Failed to start';status(e.message);return;}$('simulate').disabled=true;$('stop').disabled=false;status('Generating fixed crowd…');worker.onerror=e=>{finish('Failed');status('Simulation error: '+e.message+'; last announced drawing retained.');};worker.onmessage=({data:d})=>{try{if(d.type==='drawing'){run.last=d;persist();report(run);}else if(d.type==='result'){run.last=d;run.completed=d.index;run.results.push(d);const main=statMain;for(const t of d.winners)wins.push({...t,id:wins.length+1,date:d.date,draw:d.draw,seed,runId:run.id,mode:run.mode,avgGap:t.nums.reduce((s,n)=>s+main[n-1].gap,0)/5,pastHits:current.filter(r=>key(t)===key(r)).length});persist();report(run);if(d.winners.length)renderWins();}else if(d.type==='done')finish('Completed');else if(d.type==='error'){finish('Failed');status(d.message+'; last drawing retained.');}}catch(e){if(worker)worker.terminate();worker=null;run.state='Stopped — save failed';$('simulate').disabled=false;$('stop').disabled=true;status('Saving failed; run stopped. Export before leaving: '+e.message);}};worker.postMessage(run);};
renderWins();renderCalendar();if(journal.length)report(journal.at(-1));
try{let response;try{response=await fetch('https://raw.githubusercontent.com/daaxelv/pick3-stats/main/powerball/data/history.json',{cache:'no-store'});if(!response.ok)throw Error('Unavailable');}catch{response=await fetch('data/history.json',{cache:'no-store'});}if(!response.ok)throw Error('HTTP '+response.status);const data=await response.json();history=data.draws;current=history.filter(r=>r.date>='2015-10-07');statMain=stats(current);$('coverage').textContent=`${history.length.toLocaleString()} draws · ${data.first_date} to ${data.last_date} · ${current.length.toLocaleString()} current-format draws · ${data.missing_scheduled_draws} missing scheduled dates inside coverage. Checked ${data.checked_at}`;$('start').value=data.last_date;renderHistory();table('stats',[...stats(current).map(r=>({...r,type:'White'})),...stats(current,true).map(r=>({...r,type:'Powerball'}))],[{name:'Ball',value:r=>r.type},{name:'Number',value:r=>r.n},{name:'Times drawn',value:r=>r.hits},{name:'Draws overdue',value:r=>r.gap}]);$('rank').click();}catch(e){$('coverage').textContent='Could not load history: '+e.message;$('simulate').disabled=true;$('rank').disabled=true;}

$('backtest').onclick=()=>{if(current.length<61)return;$('backtest').disabled=true;$('backtestReport').textContent='Testing each draw with only earlier history…';const w=new Worker('backtest-worker.mjs',{type:'module'});w.onmessage=({data:d})=>{if(d.error)$('backtestReport').textContent=d.error;else table('backtestReport',Object.entries(d).map(([name,r])=>({name,...r})),[{name:'Model',value:r=>r.name},{name:'Draws tested',value:r=>r.tested},{name:'Avg actual numbers in top 5',value:r=>r.top5.toFixed(3)},{name:'Powerball top 1 hit rate',value:r=>r.mbTop1.toFixed(4)},{name:'Avg winner rank',value:r=>r.rank.toFixed(2)}]);$('backtest').disabled=false;w.terminate();};w.onerror=e=>{$('backtestReport').textContent=e.message;$('backtest').disabled=false;w.terminate();};w.postMessage(current);};
