import {scoreModel,candidateTickets} from './research.mjs';
export const TOTAL=292201338;
export const tiers=[{match:5,pb:true,label:'Jackpot'},{match:5,pb:false,label:'2nd · $1,000,000'},{match:4,pb:true,label:'3rd · $50,000'},{match:4,pb:false,label:'$100 · 4'},{match:3,pb:true,label:'$100 · 3 + PB'},{match:3,pb:false,label:'$7 · 3'},{match:2,pb:true,label:'$7 · 2 + PB'},{match:1,pb:true,label:'$4 · 1 + PB'},{match:0,pb:true,label:'$4 · PB'}];
export function choose(n,k){if(k<0||k>n)return 0;let c=1;for(let i=1;i<=k;i++)c=c*(n-i+1)/i;return Math.round(c);}
export const fullCounts=()=>tiers.map(t=>choose(5,t.match)*choose(64,5-t.match)*(t.pb?1:25));
export function key(t){return t.nums.join('-')+'|'+t.pb;}
export function tier(ticket,draw){const m=ticket.nums.filter(n=>draw.nums.includes(n)).length;return tiers.findIndex(t=>t.match===m&&t.pb===(ticket.pb===draw.pb));}
export function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
export function randomTicket(random=Math.random,focus=false){const nums=focus?[4]:[];while(nums.length<5){const n=1+Math.floor(random()*69);if(!nums.includes(n))nums.push(n);}return {nums:nums.sort((a,b)=>a-b),pb:focus?4:1+Math.floor(random()*26)};}
export function nextDate(day){const d=new Date(day+'T12:00:00Z');if(!Number.isFinite(d.getTime()))throw Error('Invalid calendar date');do{d.setUTCDate(d.getUTCDate()+1);}while(![1,3,6].includes(d.getUTCDay()));return d.toISOString().slice(0,10);}
export function stats(rows,ball=false){const max=ball?26:69;return Array.from({length:max},(_,i)=>{const n=i+1;let hits=0,last=-1;rows.forEach((r,j)=>{if(ball?r.pb===n:r.nums.includes(n)){hits++;last=j;}});return {n,hits,gap:last<0?rows.length:rows.length-1-last};});}
export function candidates(rows,algorithm='frequency',focus=false){const random=rng(104),seen=new Set(),out=[],main=stats(rows),pb=stats(rows,true);if(['origin','physical'].includes(algorithm)){const weights=scoreModel(rows,nextDate(rows.at(-1).date),algorithm);return candidateTickets(weights,10,focus).map((t,i)=>({nums:t.nums,pb:t.mb,id:i+1,score:t.score,avgGap:t.nums.reduce((s,n)=>s+main[n-1].gap,0)/5,pastHits:rows.filter(r=>key({nums:t.nums,pb:t.mb})===key(r)).length}));}const value=r=>algorithm==='overdue'?r.gap+1:r.hits+1;const weighted=(list)=>{let x=random()*list.reduce((s,r)=>s+value(r),0);for(const r of list){x-=value(r);if(x<0)return r.n;}return list.at(-1).n;};while(out.length<10){const nums=focus?[4]:[];while(nums.length<5){const n=algorithm==='uniform'?1+Math.floor(random()*69):weighted(main);if(!nums.includes(n))nums.push(n);}const t={nums:nums.sort((a,b)=>a-b),pb:focus?4:algorithm==='uniform'?1+Math.floor(random()*26):weighted(pb)};if(!seen.has(key(t))){seen.add(key(t));out.push(t);}}return out.map((t,i)=>({...t,id:i+1,avgGap:t.nums.reduce((s,n)=>s+main[n-1].gap,0)/5,pastHits:rows.filter(r=>key(t)===key(r)).length}));}
// Representatives are drawn from the complete ticket space; counts are exact, not Monte Carlo.
export function witnesses(draw,focus=false){const outside=Array.from({length:69},(_,i)=>i+1).filter(n=>!draw.nums.includes(n));return tiers.slice(0,3).map(t=>({nums:[...draw.nums.slice(0,t.match),...outside.slice(0,5-t.match)].sort((a,b)=>a-b),pb:t.pb?draw.pb:draw.pb===26?1:draw.pb+1}));}
